.TH evince 1 2005\-02\-21  
.SH NAME
evince \- view PostScript and PDF documents
.SH SYNOPSIS
\fBevince\fR [\fBfile\fR]
.SH DESCRIPTION
evince is a GNOME program for viewing
PostScript (PS) and Portable Document Format (PDF) documents.
It uses GhostScript for showing PS, and XPDF for showing PDF.
.SH OPTIONS
evince obeys all normal GNOME and GTK+ 
command line options, and has no application specific options.
.SH "SEE ALSO"
\fBgnome\-options\fR(7),
\fBgtk\-options\fR(7).
.PP
http://www.gnome.org/projects/evince/
